# Generated by Django 4.1.3 on 2022-11-24 11:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('title', models.CharField(max_length=60, verbose_name='название')),
                ('image', models.ImageField(upload_to='tests_images', verbose_name='изображение')),
                ('description', models.TextField(verbose_name='описание')),
                ('time', models.PositiveIntegerField(verbose_name='время завершения')),
            ],
            options={
                'verbose_name': 'тест',
                'verbose_name_plural': 'тесты',
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='UsersTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.test', verbose_name='тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'тест пользователя',
                'verbose_name_plural': 'тесты пользователя',
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('title', models.CharField(max_length=250, verbose_name='вопрос')),
                ('first_answer', models.CharField(max_length=250, verbose_name='превый вариант')),
                ('second_answer', models.CharField(max_length=250, verbose_name='второй вариант')),
                ('third_answer', models.CharField(max_length=250, verbose_name='третий вариант')),
                ('forth_answer', models.CharField(max_length=250, verbose_name='четвертый вариант')),
                ('true_answer', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='правильный вариант')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.test', verbose_name='тест')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='IncorrectAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('answer', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='выбранный вариант')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.question', verbose_name='вопрос')),
                ('user_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incorrect_answers', to='core.userstest', verbose_name='тест пользователь')),
            ],
            options={
                'verbose_name': 'неправильный ответ',
                'verbose_name_plural': 'неправильные ответы',
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
    ]
