# Generated by Django 4.1.3 on 2022-12-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explaining',
            field=models.TextField(default='', verbose_name='объяснение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tests_images', verbose_name='изображение'),
        ),
    ]
