# Generated by Django 4.1.3 on 2022-12-13 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_test_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incorrectanswers',
            name='answer',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='выбранный вариант'),
        ),
    ]
