# Generated by Django 4.1.3 on 2022-12-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_incorrectanswers_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstest',
            name='status',
            field=models.CharField(choices=[('completed', 'Завершенный'), ('in_progress', 'В ходе выполнения')], default='in_progress', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.PositiveIntegerField(help_text='Указывается в секундах', verbose_name='время завершения'),
        ),
    ]
